export enum ProgramCategory {
  ENGINEERING = 'ENGINEERING',
  IT = 'IT',
  HEALTH_SCIENCES = 'HEALTH_SCIENCES',
  BUSINESS = 'BUSINESS',
  ENERGY = 'ENERGY',
  AGRICULTURE = 'AGRICULTURE',
  TOURISM = 'TOURISM',
  ARTS = 'ARTS',
  EDUCATION = 'EDUCATION',
  OTHER = 'OTHER',
}
