export enum PostCategory {
  GENERAL = 'GENERAL',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  QUESTION = 'QUESTION',
  DISCUSSION = 'DISCUSSION',
  STUDY_HELP = 'STUDY_HELP',
  EVENT = 'EVENT',
  CAREER = 'CAREER',
  ADMISSION = 'ADMISSION',
  REVIEW = 'REVIEW',
}
