export enum NewsCategory {
  GENERAL = 'GENERAL',
  ACADEMIC = 'ACADEMIC',
  ADMISSIONS = 'ADMISSIONS',
  EVENTS = 'EVENTS',
  RESEARCH = 'RESEARCH',
  STUDENT_LIFE = 'STUDENT_LIFE',
  CAREER = 'CAREER',
  ACHIEVEMENTS = 'ACHIEVEMENTS',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  PARTNERSHIPS = 'PARTNERSHIPS',
}
